<!DOCTYPE html>
<!--[if IE 8]>
<html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]>
<html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Essentia.cloud the manifest of the essentia." name="description">
    <meta content="essentia essencia cloud system" name="keywords">
    <meta content="Németh Zoltán" name="author">
    <link rel="shortcut icon" href="favicon.ico">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|PT+Sans+Narrow|Source+Sans+Pro:200,300,400,600,700,900&amp;subset=all"
          rel="stylesheet" type="text/css">
    <link href="assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/pages/css/animate.css" rel="stylesheet">
    <link href="assets/plugins/fancybox/source/jquery.fancybox.css" rel="stylesheet">
    <link href="assets/plugins/owl.carousel/assets/owl.carousel.css" rel="stylesheet">
    <link href="assets/pages/css/components.css" rel="stylesheet">
    <link href="assets/pages/css/slider.css" rel="stylesheet">
    <link href="assets/corporate/css/style.css" rel="stylesheet">
    <link href="assets/corporate/css/style-responsive.css" rel="stylesheet">
    <link href="assets/corporate/css/themes/red.css" rel="stylesheet" id="style-color">
    <link href="assets/corporate/css/custom.css" rel="stylesheet">
    <title><?php echo $this->layout['meta_title']; ?></title>
</head>
<body class="corporate">
<div class="pre-header">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6 additional-shop-info">
                <ul class="list-unstyled list-inline">
                    <li><i class="fa fa-phone"></i><span>+1 456 6717</span></li>
                    <li><i class="fa fa-envelope-o"></i><span>info@keenthemes.com</span></li>
                </ul>
            </div>
            <div class="col-md-6 col-sm-6 additional-nav">
                <ul class="list-unstyled list-inline pull-right">
                    <li><a href="#">Log In</a></li>
                    <li><a href="#">Registration</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="header">
    <div class="container">
        <a class="site-logo" href="index.html"><img src="assets/corporate/img/logos/logo-corp-red.png" alt="Metronic FrontEnd"></a>
        <a href="javascript:void(0);" class="mobi-toggler"><i class="fa fa-bars"></i></a>
        <div class="header-navigation pull-right font-transform-inherit">
            <ul>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="javascript:;">
                        Home

                    </a>

                    <ul class="dropdown-menu">
                        <li class="active"><a href="index.html">Home Default</a></li>
                        <li><a href="index-header-fix.html">Home with Header Fixed</a></li>
                        <li><a href="index-without-topbar.html">Home without Top Bar</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="javascript:;">Pages</a>
                    <ul class="dropdown-menu">
                        <li><a href="page-about.html">About Us</a></li>
                        <li><a href="page-services.html">Services</a></li>
                        <li><a href="page-prices.html">Prices</a></li>
                        <li><a href="page-faq.html">FAQ</a></li>
                        <li><a href="page-gallery.html">Gallery</a></li>
                        <li><a href="page-search-result.html">Search Result</a></li>
                        <li><a href="page-404.html">404</a></li>
                        <li><a href="page-500.html">500</a></li>
                        <li><a href="page-login.html">Login Page</a></li>
                        <li><a href="page-forgotton-password.html">Forget Password</a></li>
                        <li><a href="page-reg-page.html">Signup Page</a></li>
                        <li><a href="page-careers.html">Careers</a></li>
                        <li><a href="page-site-map.html">Site Map</a></li>
                        <li><a href="page-contacts.html">Contact</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="javascript:;">Multilevel</a>
                    <ul class="dropdown-menu">
                        <li class="dropdown-submenu">
                            <a href="index.html">Multi level <i class="fa fa-angle-right"></i></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="index.html">Second Level Link</a></li>
                                <li><a href="index.html">Second Level Link</a></li>
                                <li class="dropdown-submenu">
                                    <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="javascript:;">
                                        Second Level Link
                                        <i class="fa fa-angle-right"></i>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a href="index.html">Third Level Link</a></li>
                                        <li><a href="index.html">Third Level Link</a></li>
                                        <li><a href="index.html">Third Level Link</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="javascript:;">
                        Portfolio

                    </a>

                    <ul class="dropdown-menu">
                        <li><a href="portfolio-4.html">Portfolio 4</a></li>
                        <li><a href="portfolio-3.html">Portfolio 3</a></li>
                        <li><a href="portfolio-2.html">Portfolio 2</a></li>
                        <li><a href="portfolio-item.html">Portfolio Item</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="javascript:;">
                        Blog

                    </a>

                    <ul class="dropdown-menu">
                        <li><a href="blog.html">Blog Page</a></li>
                        <li><a href="blog-item.html">Blog Item</a></li>
                    </ul>
                </li>

                <li class="menu-search">
                    <span class="sep"></span>
                    <i class="fa fa-search search-btn"></i>
                    <div class="search-box">
                        <form action="#">
                            <div class="input-group">
                                <input type="text" placeholder="Search" class="form-control">
                                <span class="input-group-btn">
                      <button class="btn btn-primary" type="submit">Search</button>
                    </span>
                            </div>
                        </form>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
<?php
echo $this->content;
?>
</body>
</html>